name: run_walk_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+24

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  nowplaying: ^3.0.2
  audioplayers: ^6.0.0
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  http: ^1.2.2
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  google_fonts: ^6.2.0
  url_launcher: ^6.3.0

  wearable_rotary: ^2.0.0


  device_info_plus: ^11.1.1


  # ✅ FIREBASE ATUALIZADO
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  firebase_storage: ^12.4.9
  firebase_analytics: ^11.5.2
  firebase_messaging: ^15.2.9

  connectivity_plus: ^6.1.0
  shared_preferences: ^2.3.2
  package_info_plus: ^8.3.1

  #image_cropper: ^5.0.1
  flutter_image_compress: ^2.3.0
  #video_compress: ^3.1.2

  flutter_background_service: ^5.0.6
  flutter_background_service_android: ^6.0.4
  flutter_markdown: ^0.6.18
  path_provider: ^2.1.4

  flutter_local_notifications: ^17.2.1
  permission_handler: ^11.0.1

  # Localização e GPS
  location: ^5.0.3
  geolocator: ^13.0.2
  flutter_geo_hash: ^0.0.6

  introduction_screen: ^3.1.12

  confetti: ^0.7.0

  # Google Maps
  google_maps_flutter: ^2.12.1

  # Auth Google
  google_sign_in: ^6.2.1

  # Estado
  provider: ^6.1.2
  flutter_riverpod: ^2.6.1

  # Datas e formatação
  intl: ^0.20.2
  timeago: ^3.7.0

  flutter_animate: ^4.5.0
  reaction_button: ^0.0.7

  video_player: ^2.9.1
  lottie: ^3.1.0

  share_plus: ^10.0.2
  qr_flutter: ^4.1.0
  model_viewer_plus: ^1.9.1
  flutter_launcher_icons: ^0.14.4
  google_mobile_ads: ^5.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  screenshot: 2.1.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo_principal.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/logo_principal.png"

flutter:
  uses-material-design: true
  assets:
    - assets/map_style.json
    - assets/map_style_day.json
    - assets/click.mp3
    - assets/sounds/
    - assets/icon/logo_principal.png
    - assets/videos/splash.mp4
    - assets/audio/pre_run_1.mp3
    - assets/audio/pre_run_2.mp3
    - assets/audio/pre_run_3.mp3
    - assets/audio/pre_run_4.mp3
    - assets/audio/pre_run_5.mp3
    - assets/audio/pre_run_6.mp3
    - assets/audio/pre_run_7.mp3
    - assets/lottie/
    - assets/frames/
